// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_EMBER_TYPES
#include EMBER_AF_API_COMMAND_INTERPRETER2

void advertiseCommand(void);
void coapDeleteCommand(void);
void coapGetCommand(void);
void coapListenCommand(void);
void coapPostCommand(void);
void coapPutCommand(void);
static EmberCommandEntry emberCommandCoapTable[] = {
  emberCommandEntryAction("delete", coapDeleteCommand, "bb", ""),
  emberCommandEntryAction("get", coapGetCommand, "bb", ""),
  emberCommandEntryAction("listen", coapListenCommand, "b", ""),
  emberCommandEntryAction("post", coapPostCommand, "bbb*", ""),
  emberCommandEntryAction("put", coapPutCommand, "bbb*", ""),
  emberCommandEntryTerminator(),
};
void expectCommand(void);
void emberPrintCommandTable(void);
void icmpListenCommand(void);
void icmpPingCommand(void);
static EmberCommandEntry emberCommandIcmpTable[] = {
  emberCommandEntryAction("listen", icmpListenCommand, "b", ""),
  emberCommandEntryAction("ping", icmpPingCommand, "bv*", ""),
  emberCommandEntryTerminator(),
};
void networkManagementInfoCommand(void);
void emberAttachToNetwork(void);
void networkManagementCommissionCommand(void);
void networkManagementCommissioningStartCommand(void);
void emberStopCommissioning(void);
static EmberCommandEntry emberCommandNetworkManagementCommissioningTable[] = {
  emberCommandEntryAction("start", networkManagementCommissioningStartCommand, "b", ""),
  emberCommandEntryAction("stop", emberStopCommissioning, "", ""),
  emberCommandEntryTerminator(),
};
void networkManagementFormCommand(void);
void networkManagementConfigureGatewayCommand(void);
void networkManagementGetGlobalAddressesCommand(void);
void emberGetGlobalPrefixes(void);
void networkManagementJoinCommand(void);
void networkManagementJoinCommissionedCommand(void);
void networkManagementListenersCommand(void);
void emberResetNetworkState(void);
void emberResumeNetwork(void);
void networkManagementScanCommand(void);
void networkManagementScanCommand(void);
void emberStopScan(void);
static EmberCommandEntry emberCommandNetworkManagementScanTable[] = {
  emberCommandEntryAction("active", networkManagementScanCommand, "u*", ""),
  emberCommandEntryAction("energy", networkManagementScanCommand, "u*", ""),
  emberCommandEntryAction("stop", emberStopScan, "", ""),
  emberCommandEntryTerminator(),
};
void networkManagementSetJoinKeyCommand(void);
void networkManagementSetJoiningModeCommand(void);
void networkManagementSetMasterKeyCommand(void);
void networkManagementSteeringAddCommand(void);
void emberSendSteeringData(void);
static EmberCommandEntry emberCommandNetworkManagementSteeringTable[] = {
  emberCommandEntryAction("add", networkManagementSteeringAddCommand, "b", ""),
  emberCommandEntryAction("send", emberSendSteeringData, "", ""),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandNetworkManagementTable[] = {
  emberCommandEntryAction("attach", emberAttachToNetwork, "", ""),
  emberCommandEntryAction("commission", networkManagementCommissionCommand, "uwbbbbv*", ""),
  emberCommandEntrySubMenu("commissioning", emberCommandNetworkManagementCommissioningTable, ""),
  emberCommandEntryAction("form", networkManagementFormCommand, "usub*", ""),
  emberCommandEntryAction("gateway", networkManagementConfigureGatewayCommand, "uubuww", ""),
  emberCommandEntryAction("global-addresses", networkManagementGetGlobalAddressesCommand, "b*", ""),
  emberCommandEntryAction("global-prefixes", emberGetGlobalPrefixes, "", ""),
  emberCommandEntryAction("join", networkManagementJoinCommand, "usubbvb", ""),
  emberCommandEntryAction("join-commissioned", networkManagementJoinCommissionedCommand, "suu*", ""),
  emberCommandEntryAction("listeners", networkManagementListenersCommand, "", ""),
  emberCommandEntryAction("reset", emberResetNetworkState, "", ""),
  emberCommandEntryAction("resume", emberResumeNetwork, "", ""),
  emberCommandEntrySubMenu("scan", emberCommandNetworkManagementScanTable, ""),
  emberCommandEntryAction("set-join-key", networkManagementSetJoinKeyCommand, "bb*", ""),
  emberCommandEntryAction("set-joining-mode", networkManagementSetJoiningModeCommand, "uu", ""),
  emberCommandEntryAction("set-master-key", networkManagementSetMasterKeyCommand, "b", ""),
  emberCommandEntrySubMenu("steering", emberCommandNetworkManagementSteeringTable, ""),
  emberCommandEntryTerminator(),
};
void emberResetMicro(void);
void udpListenCommand(void);
void udpSendCommand(void);
static EmberCommandEntry emberCommandUdpTable[] = {
  emberCommandEntryAction("listen", udpListenCommand, "vb", ""),
  emberCommandEntryAction("send", udpSendCommand, "bvvb", ""),
  emberCommandEntryTerminator(),
};
void emberGetVersions(void);
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryAction("advertise", advertiseCommand, "", ""),
  emberCommandEntrySubMenu("coap", emberCommandCoapTable, ""),
  emberCommandEntryAction("expect", expectCommand, "bb*", ""),
  emberCommandEntryAction("help", emberPrintCommandTable, "", ""),
  emberCommandEntrySubMenu("icmp", emberCommandIcmpTable, ""),
  emberCommandEntryAction("info", networkManagementInfoCommand, "", ""),
  emberCommandEntrySubMenu("network-management", emberCommandNetworkManagementTable, ""),
  emberCommandEntryAction("reset", emberResetMicro, "", ""),
  emberCommandEntrySubMenu("udp", emberCommandUdpTable, ""),
  emberCommandEntryAction("versions", emberGetVersions, "", ""),
  emberCommandEntryTerminator(),
};
