// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __THREAD_CONFIG__
#define __THREAD_CONFIG__




// Top level macros
#define EMBER_AF_DEVICE_NAME "client_2"


// Generated setup headers that are included automatically
#include "thread-debug-print.h"


// Generated plugin macros

// Use this macro to check if ADC plugin is included
#define EMBER_AF_PLUGIN_ADC

// Use this macro to check if Address Configuration Debug plugin is included
#define EMBER_AF_PLUGIN_ADDRESS_CONFIGURATION_DEBUG

// Use this macro to check if Antenna Stub plugin is included
#define EMBER_AF_PLUGIN_ANTENNA_STUB

// Use this macro to check if Button plugin is included
#define EMBER_AF_PLUGIN_BUTTON

// Use this macro to check if Buzzer plugin is included
#define EMBER_AF_PLUGIN_BUZZER

// Use this macro to check if CLI plugin is included
#define EMBER_AF_PLUGIN_CLI

// Use this macro to check if CoAP CLI plugin is included
#define EMBER_AF_PLUGIN_COAP_CLI

// Use this macro to check if CoAP Dispatch plugin is included
#define EMBER_AF_PLUGIN_COAP_DISPATCH

// Use this macro to check if Command Interpreter plugin is included
#define EMBER_AF_PLUGIN_COMMAND_INTERPRETER2

// Use this macro to check if Debug Print plugin is included
#define EMBER_AF_PLUGIN_DEBUG_PRINT
// User options for plugin Debug Print
#define EMBER_AF_DEBUG_PRINT_USE_PORT

// Use this macro to check if Dynamic Host Configuration Protocol (DHCP) Client plugin is included
#define EMBER_AF_PLUGIN_DHCP_CLIENT

// Use this macro to check if DHCP Library plugin is included
#define EMBER_AF_PLUGIN_DHCP_LIBRARY

// Use this macro to check if Diagnostic plugin is included
#define EMBER_AF_PLUGIN_DIAGNOSTIC

// Use this macro to check if Global Address/Prefix Debug plugin is included
#define EMBER_AF_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG

// Use this macro to check if HAL Library plugin is included
#define EMBER_AF_PLUGIN_HAL_LIBRARY

// Use this macro to check if Heartbeat plugin is included
#define EMBER_AF_PLUGIN_HEARTBEAT
// User options for plugin Heartbeat
#define EMBER_AF_PLUGIN_HEARTBEAT_PERIOD_QS 1

// Use this macro to check if ICMP CLI plugin is included
#define EMBER_AF_PLUGIN_ICMP_CLI

// Use this macro to check if ICMP Debug plugin is included
#define EMBER_AF_PLUGIN_ICMP_DEBUG

// Use this macro to check if Idle/Sleep plugin is included
#define EMBER_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define EMBER_AF_PLUGIN_IDLE_SLEEP_MINIMUM_SLEEP_DURATION_MS 5

// Use this macro to check if LED plugin is included
#define EMBER_AF_PLUGIN_LED

// Use this macro to check if Main plugin is included
#define EMBER_AF_PLUGIN_MAIN

// Use this macro to check if mbed TLS Cryptographic Library plugin is included
#define EMBER_AF_PLUGIN_MBEDTLS_LIBRARY

// Use this macro to check if Manufacturing Library plugin is included
#define EMBER_AF_PLUGIN_MFGLIB_LIBRARY

// Use this macro to check if Network Management CLI plugin is included
#define EMBER_AF_PLUGIN_NETWORK_MANAGEMENT_CLI

// Use this macro to check if Scan Debug plugin is included
#define EMBER_AF_PLUGIN_SCAN_DEBUG

// Use this macro to check if Serial plugin is included
#define EMBER_AF_PLUGIN_SERIAL

// Use this macro to check if Simulated EEPROM version 1 Library plugin is included
#define EMBER_AF_PLUGIN_SIM_EEPROM1
// User options for plugin Simulated EEPROM version 1 Library

// Use this macro to check if Stateless Address Autoconfiguration (SLAAC) Client plugin is included
#define EMBER_AF_PLUGIN_SLAAC_CLIENT

// Use this macro to check if TFTP Bootload Target plugin is included
#define EMBER_AF_PLUGIN_TFTP_BOOTLOAD_TARGET

// Use this macro to check if Thread Stack Library plugin is included
#define EMBER_AF_PLUGIN_THREAD_STACK

// Use this macro to check if UDP CLI plugin is included
#define EMBER_AF_PLUGIN_UDP_CLI

// Use this macro to check if Version Debug plugin is included
#define EMBER_AF_PLUGIN_VERSION_DEBUG


// Generated API headers

// API adc-cortexm3 from ADC plugin
#define EMBER_AF_API_ADC_CORTEXM3 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/cortexm3/adc.h"

// API adc from ADC plugin
#define EMBER_AF_API_ADC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/adc.h"

// API antenna from Antenna Stub plugin
#define EMBER_AF_API_ANTENNA "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/antenna.h"

// API button from Button plugin
#define EMBER_AF_API_BUTTON "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/button.h"

// API buzzer from Buzzer plugin
#define EMBER_AF_API_BUZZER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/buzzer.h"

// API coap-dispatch from CoAP Dispatch plugin
#define EMBER_AF_API_COAP_DISPATCH "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/app/thread/plugin/coap-dispatch/coap-dispatch.h"

// API command-interpreter2 from Command Interpreter plugin
#define EMBER_AF_API_COMMAND_INTERPRETER2 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/app/util/serial/command-interpreter2.h"

// API debug-print from Debug Print plugin
#define EMBER_AF_API_DEBUG_PRINT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/app/thread/plugin/debug-print/debug-print.h"

// API diagnostic-cortexm3 from Diagnostic plugin
#define EMBER_AF_API_DIAGNOSTIC_CORTEXM3 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/cortexm3/diagnostic.h"

// API diagnostic from Diagnostic plugin
#define EMBER_AF_API_DIAGNOSTIC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/diagnostic.h"

// API crc from HAL Library plugin
#define EMBER_AF_API_CRC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/crc.h"

// API endian from HAL Library plugin
#define EMBER_AF_API_ENDIAN "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/endian.h"

// API hal from HAL Library plugin
#define EMBER_AF_API_HAL "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/hal.h"

// API random from HAL Library plugin
#define EMBER_AF_API_RANDOM "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/random.h"

// API system-timer from HAL Library plugin
#define EMBER_AF_API_SYSTEM_TIMER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/system-timer.h"

// API token-cortexm3 from HAL Library plugin
#define EMBER_AF_API_TOKEN_CORTEXM3 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/cortexm3/token.h"

// API token from HAL Library plugin
#define EMBER_AF_API_TOKEN "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/token.h"

// API led from LED plugin
#define EMBER_AF_API_LED "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/led.h"

// API mfglib from Manufacturing Library plugin
#define EMBER_AF_API_MFGLIB "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/mfglib.h"

// API serial from Serial plugin
#define EMBER_AF_API_SERIAL "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/plugin/serial/serial.h"

// API sim-eeprom from Simulated EEPROM version 1 Library plugin
#define EMBER_AF_API_SIM_EEPROM "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/platform/base/hal/micro/sim-eeprom.h"

// API tftp from TFTP Bootload Target plugin
#define EMBER_AF_API_TFTP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/app/util/bootload/tftp/tftp.h"

// API tftp-bootloader from TFTP Bootload Target plugin
#define EMBER_AF_API_TFTP_BOOTLOADER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/app/util/bootload/tftp-bootloader/tftp-bootloader.h"

// API tftp-server from TFTP Bootload Target plugin
#define EMBER_AF_API_TFTP_SERVER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/app/util/bootload/tftp/server/tftp-server.h"

// API buffer-management from Thread Stack Library plugin
#define EMBER_AF_API_BUFFER_MANAGEMENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/framework/buffer-management.h"

// API child from Thread Stack Library plugin
#define EMBER_AF_API_CHILD "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/child.h"

// API coap-diagnostic from Thread Stack Library plugin
#define EMBER_AF_API_COAP_DIAGNOSTIC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/coap-diagnostic.h"

// API coap from Thread Stack Library plugin
#define EMBER_AF_API_COAP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/coap.h"

// API event-queue from Thread Stack Library plugin
#define EMBER_AF_API_EVENT_QUEUE "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/framework/event-queue.h"

// API event from Thread Stack Library plugin
#define EMBER_AF_API_EVENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/event.h"

// API icmp from Thread Stack Library plugin
#define EMBER_AF_API_ICMP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/icmp.h"

// API network-management from Thread Stack Library plugin
#define EMBER_AF_API_NETWORK_MANAGEMENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/network-management.h"

// API stack-info from Thread Stack Library plugin
#define EMBER_AF_API_STACK_INFO "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/stack-info.h"

// API stack from Thread Stack Library plugin
#define EMBER_AF_API_STACK "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/ember.h"

// API tcp from Thread Stack Library plugin
#define EMBER_AF_API_TCP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/tcp.h"

// API udp-peer from Thread Stack Library plugin
#define EMBER_AF_API_UDP_PEER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/udp-peer.h"

// API udp from Thread Stack Library plugin
#define EMBER_AF_API_UDP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/stacks/thread/v2.0.0.0/protocol/thread_2.0/stack/include/udp.h"


// Custom macros
#ifdef APP_SERIAL
#undef APP_SERIAL
#endif
#define APP_SERIAL 1

#ifdef EMBER_ASSERT_SERIAL_PORT
#undef EMBER_ASSERT_SERIAL_PORT
#endif
#define EMBER_ASSERT_SERIAL_PORT 1

#ifdef EMBER_AF_BAUD_RATE
#undef EMBER_AF_BAUD_RATE
#endif
#define EMBER_AF_BAUD_RATE 115200

#ifdef EMBER_SERIAL0_MODE
#undef EMBER_SERIAL0_MODE
#endif
#define EMBER_SERIAL0_MODE EMBER_SERIAL_FIFO

#ifdef EMBER_SERIAL0_RX_QUEUE_SIZE
#undef EMBER_SERIAL0_RX_QUEUE_SIZE
#endif
#define EMBER_SERIAL0_RX_QUEUE_SIZE 128

#ifdef EMBER_SERIAL0_TX_QUEUE_SIZE
#undef EMBER_SERIAL0_TX_QUEUE_SIZE
#endif
#define EMBER_SERIAL0_TX_QUEUE_SIZE 128

#ifdef EMBER_SERIAL0_BLOCKING
#undef EMBER_SERIAL0_BLOCKING
#endif
#define EMBER_SERIAL0_BLOCKING

#ifdef EMBER_SERIAL1_MODE
#undef EMBER_SERIAL1_MODE
#endif
#define EMBER_SERIAL1_MODE EMBER_SERIAL_FIFO

#ifdef EMBER_SERIAL1_RX_QUEUE_SIZE
#undef EMBER_SERIAL1_RX_QUEUE_SIZE
#endif
#define EMBER_SERIAL1_RX_QUEUE_SIZE 128

#ifdef EMBER_SERIAL1_TX_QUEUE_SIZE
#undef EMBER_SERIAL1_TX_QUEUE_SIZE
#endif
#define EMBER_SERIAL1_TX_QUEUE_SIZE 128

#ifdef EMBER_SERIAL1_BLOCKING
#undef EMBER_SERIAL1_BLOCKING
#endif
#define EMBER_SERIAL1_BLOCKING

#ifdef EMBER_AF_SERIAL_PORT_INIT
#undef EMBER_AF_SERIAL_PORT_INIT
#endif
#define EMBER_AF_SERIAL_PORT_INIT() \
  do { \
    emberSerialInit(0, BAUD_115200, PARITY_NONE, 1); \
    emberSerialInit(1, BAUD_115200, PARITY_NONE, 1); \
  } while (0)

#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32MG1P232F256GM48

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY M

#ifdef EMBER_AF_RADIO_GENERATION
#undef EMBER_AF_RADIO_GENERATION
#endif
#define EMBER_AF_RADIO_GENERATION 1

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 232

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 256K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 48

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32MG1P232F256GM48

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY M

#ifdef EMBER_AF_MCU_GENERATION
#undef EMBER_AF_MCU_GENERATION
#endif
#define EMBER_AF_MCU_GENERATION 1

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 232

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 256K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 48

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4151A


// Coap Dispatch macros
#ifdef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#undef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#endif
#define EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH 16



#endif // __THREAD_CONFIG__
