// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __THREAD_EVENTS__
#define __THREAD_EVENTS__


// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void stateEventHandler(void);
extern EmberEventControl stateEventControl;

void emBootloadEventHandler(void);
extern EmberEventControl emBootloadEvent;



const EmberEventData emAppEvents[] = {
  {&stateEventControl, stateEventHandler},
  {&emBootloadEvent, emBootloadEventHandler},
  {NULL, NULL}
};
#endif // __THREAD_EVENTS__
