// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __EMBER_AF_DEBUG_PRINTING_CONFIGURATION__
#define __EMBER_AF_DEBUG_PRINTING_CONFIGURATION__




// This file contains the generated macros for the debug printing
// Global macro, if this is commented out, there is no printing
#define EMBER_AF_PRINT_ENABLE



// Generated bit array and name array that is used by thedebug printing library.
#define EMBER_AF_PRINT_CORE 0x0001
#define EMBER_AF_PRINT_APP 0x0002
#define EMBER_AF_PRINT_BITS { 0x03 }
#define EMBER_AF_PRINT_NAMES { \
  "Core",\
  "Application",\
  NULL\
}
#define EMBER_AF_PRINT_NAME_NUMBER 2


// Generated functions for use within plugin ADC
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ADC)
#define emberAfPluginAdcPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_ADC, __VA_ARGS__)
#define emberAfPluginAdcPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_ADC,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginAdcFlush()
#define emberAfPluginAdcDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_ADC) ) { x; }
#define emberAfPluginAdcPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_ADC, (buffer), (len), (withSpace))
#define emberAfPluginAdcPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_ADC, (buffer))
#else
#define emberAfPluginAdcPrint(...)
#define emberAfPluginAdcPrintln(...)
#define emberAfPluginAdcFlush()
#define emberAfPluginAdcDebugExec(x)
#define emberAfPluginAdcPrintBuffer(buffer, len, withSpace)
#define emberAfPluginAdcPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ADC)


// Generated functions for use within plugin Address Configuration Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG)
#define emberAfPluginAddressConfigurationDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG, __VA_ARGS__)
#define emberAfPluginAddressConfigurationDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginAddressConfigurationDebugFlush()
#define emberAfPluginAddressConfigurationDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG) ) { x; }
#define emberAfPluginAddressConfigurationDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG, (buffer), (len), (withSpace))
#define emberAfPluginAddressConfigurationDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG, (buffer))
#else
#define emberAfPluginAddressConfigurationDebugPrint(...)
#define emberAfPluginAddressConfigurationDebugPrintln(...)
#define emberAfPluginAddressConfigurationDebugFlush()
#define emberAfPluginAddressConfigurationDebugDebugExec(x)
#define emberAfPluginAddressConfigurationDebugPrintBuffer(buffer, len, withSpace)
#define emberAfPluginAddressConfigurationDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ADDRESS_CONFIGURATION_DEBUG)


// Generated functions for use within plugin Antenna Stub
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB)
#define emberAfPluginAntennaStubPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB, __VA_ARGS__)
#define emberAfPluginAntennaStubPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginAntennaStubFlush()
#define emberAfPluginAntennaStubDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB) ) { x; }
#define emberAfPluginAntennaStubPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB, (buffer), (len), (withSpace))
#define emberAfPluginAntennaStubPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB, (buffer))
#else
#define emberAfPluginAntennaStubPrint(...)
#define emberAfPluginAntennaStubPrintln(...)
#define emberAfPluginAntennaStubFlush()
#define emberAfPluginAntennaStubDebugExec(x)
#define emberAfPluginAntennaStubPrintBuffer(buffer, len, withSpace)
#define emberAfPluginAntennaStubPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ANTENNA_STUB)


// Generated functions for use within plugin Button
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_BUTTON)
#define emberAfPluginButtonPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_BUTTON, __VA_ARGS__)
#define emberAfPluginButtonPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_BUTTON,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginButtonFlush()
#define emberAfPluginButtonDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_BUTTON) ) { x; }
#define emberAfPluginButtonPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_BUTTON, (buffer), (len), (withSpace))
#define emberAfPluginButtonPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_BUTTON, (buffer))
#else
#define emberAfPluginButtonPrint(...)
#define emberAfPluginButtonPrintln(...)
#define emberAfPluginButtonFlush()
#define emberAfPluginButtonDebugExec(x)
#define emberAfPluginButtonPrintBuffer(buffer, len, withSpace)
#define emberAfPluginButtonPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_BUTTON)


// Generated functions for use within plugin Buzzer
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_BUZZER)
#define emberAfPluginBuzzerPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_BUZZER, __VA_ARGS__)
#define emberAfPluginBuzzerPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_BUZZER,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginBuzzerFlush()
#define emberAfPluginBuzzerDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_BUZZER) ) { x; }
#define emberAfPluginBuzzerPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_BUZZER, (buffer), (len), (withSpace))
#define emberAfPluginBuzzerPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_BUZZER, (buffer))
#else
#define emberAfPluginBuzzerPrint(...)
#define emberAfPluginBuzzerPrintln(...)
#define emberAfPluginBuzzerFlush()
#define emberAfPluginBuzzerDebugExec(x)
#define emberAfPluginBuzzerPrintBuffer(buffer, len, withSpace)
#define emberAfPluginBuzzerPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_BUZZER)


// Generated functions for use within plugin CLI
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_CLI)
#define emberAfPluginCliPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_CLI, __VA_ARGS__)
#define emberAfPluginCliPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_CLI,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginCliFlush()
#define emberAfPluginCliDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_CLI) ) { x; }
#define emberAfPluginCliPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_CLI, (buffer), (len), (withSpace))
#define emberAfPluginCliPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_CLI, (buffer))
#else
#define emberAfPluginCliPrint(...)
#define emberAfPluginCliPrintln(...)
#define emberAfPluginCliFlush()
#define emberAfPluginCliDebugExec(x)
#define emberAfPluginCliPrintBuffer(buffer, len, withSpace)
#define emberAfPluginCliPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_CLI)


// Generated functions for use within plugin CoAP CLI
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COAP_CLI)
#define emberAfPluginCoapCliPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_COAP_CLI, __VA_ARGS__)
#define emberAfPluginCoapCliPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_COAP_CLI,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginCoapCliFlush()
#define emberAfPluginCoapCliDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_COAP_CLI) ) { x; }
#define emberAfPluginCoapCliPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_COAP_CLI, (buffer), (len), (withSpace))
#define emberAfPluginCoapCliPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_COAP_CLI, (buffer))
#else
#define emberAfPluginCoapCliPrint(...)
#define emberAfPluginCoapCliPrintln(...)
#define emberAfPluginCoapCliFlush()
#define emberAfPluginCoapCliDebugExec(x)
#define emberAfPluginCoapCliPrintBuffer(buffer, len, withSpace)
#define emberAfPluginCoapCliPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COAP_CLI)


// Generated functions for use within plugin CoAP Dispatch
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH)
#define emberAfPluginCoapDispatchPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH, __VA_ARGS__)
#define emberAfPluginCoapDispatchPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginCoapDispatchFlush()
#define emberAfPluginCoapDispatchDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH) ) { x; }
#define emberAfPluginCoapDispatchPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH, (buffer), (len), (withSpace))
#define emberAfPluginCoapDispatchPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH, (buffer))
#else
#define emberAfPluginCoapDispatchPrint(...)
#define emberAfPluginCoapDispatchPrintln(...)
#define emberAfPluginCoapDispatchFlush()
#define emberAfPluginCoapDispatchDebugExec(x)
#define emberAfPluginCoapDispatchPrintBuffer(buffer, len, withSpace)
#define emberAfPluginCoapDispatchPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COAP_DISPATCH)


// Generated functions for use within plugin Command Interpreter
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2)
#define emberAfPluginCommandInterpreter2Print(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2, __VA_ARGS__)
#define emberAfPluginCommandInterpreter2Println(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginCommandInterpreter2Flush()
#define emberAfPluginCommandInterpreter2DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2) ) { x; }
#define emberAfPluginCommandInterpreter2PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2, (buffer), (len), (withSpace))
#define emberAfPluginCommandInterpreter2PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2, (buffer))
#else
#define emberAfPluginCommandInterpreter2Print(...)
#define emberAfPluginCommandInterpreter2Println(...)
#define emberAfPluginCommandInterpreter2Flush()
#define emberAfPluginCommandInterpreter2DebugExec(x)
#define emberAfPluginCommandInterpreter2PrintBuffer(buffer, len, withSpace)
#define emberAfPluginCommandInterpreter2PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER2)


// Generated functions for use within plugin Debug Print
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT)
#define emberAfPluginDebugPrintPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT, __VA_ARGS__)
#define emberAfPluginDebugPrintPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginDebugPrintFlush()
#define emberAfPluginDebugPrintDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT) ) { x; }
#define emberAfPluginDebugPrintPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT, (buffer), (len), (withSpace))
#define emberAfPluginDebugPrintPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT, (buffer))
#else
#define emberAfPluginDebugPrintPrint(...)
#define emberAfPluginDebugPrintPrintln(...)
#define emberAfPluginDebugPrintFlush()
#define emberAfPluginDebugPrintDebugExec(x)
#define emberAfPluginDebugPrintPrintBuffer(buffer, len, withSpace)
#define emberAfPluginDebugPrintPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT)


// Generated functions for use within plugin Dynamic Host Configuration Protocol (DHCP) Client
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT)
#define emberAfPluginDhcpClientPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT, __VA_ARGS__)
#define emberAfPluginDhcpClientPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginDhcpClientFlush()
#define emberAfPluginDhcpClientDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT) ) { x; }
#define emberAfPluginDhcpClientPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT, (buffer), (len), (withSpace))
#define emberAfPluginDhcpClientPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT, (buffer))
#else
#define emberAfPluginDhcpClientPrint(...)
#define emberAfPluginDhcpClientPrintln(...)
#define emberAfPluginDhcpClientFlush()
#define emberAfPluginDhcpClientDebugExec(x)
#define emberAfPluginDhcpClientPrintBuffer(buffer, len, withSpace)
#define emberAfPluginDhcpClientPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DHCP_CLIENT)


// Generated functions for use within plugin DHCP Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY)
#define emberAfPluginDhcpLibraryPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY, __VA_ARGS__)
#define emberAfPluginDhcpLibraryPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginDhcpLibraryFlush()
#define emberAfPluginDhcpLibraryDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY) ) { x; }
#define emberAfPluginDhcpLibraryPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY, (buffer), (len), (withSpace))
#define emberAfPluginDhcpLibraryPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY, (buffer))
#else
#define emberAfPluginDhcpLibraryPrint(...)
#define emberAfPluginDhcpLibraryPrintln(...)
#define emberAfPluginDhcpLibraryFlush()
#define emberAfPluginDhcpLibraryDebugExec(x)
#define emberAfPluginDhcpLibraryPrintBuffer(buffer, len, withSpace)
#define emberAfPluginDhcpLibraryPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DHCP_LIBRARY)


// Generated functions for use within plugin Diagnostic
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC)
#define emberAfPluginDiagnosticPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC, __VA_ARGS__)
#define emberAfPluginDiagnosticPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginDiagnosticFlush()
#define emberAfPluginDiagnosticDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC) ) { x; }
#define emberAfPluginDiagnosticPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC, (buffer), (len), (withSpace))
#define emberAfPluginDiagnosticPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC, (buffer))
#else
#define emberAfPluginDiagnosticPrint(...)
#define emberAfPluginDiagnosticPrintln(...)
#define emberAfPluginDiagnosticFlush()
#define emberAfPluginDiagnosticDebugExec(x)
#define emberAfPluginDiagnosticPrintBuffer(buffer, len, withSpace)
#define emberAfPluginDiagnosticPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC)


// Generated functions for use within plugin Global Address/Prefix Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG)
#define emberAfPluginGlobalAddressPrefixDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG, __VA_ARGS__)
#define emberAfPluginGlobalAddressPrefixDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginGlobalAddressPrefixDebugFlush()
#define emberAfPluginGlobalAddressPrefixDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG) ) { x; }
#define emberAfPluginGlobalAddressPrefixDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG, (buffer), (len), (withSpace))
#define emberAfPluginGlobalAddressPrefixDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG, (buffer))
#else
#define emberAfPluginGlobalAddressPrefixDebugPrint(...)
#define emberAfPluginGlobalAddressPrefixDebugPrintln(...)
#define emberAfPluginGlobalAddressPrefixDebugFlush()
#define emberAfPluginGlobalAddressPrefixDebugDebugExec(x)
#define emberAfPluginGlobalAddressPrefixDebugPrintBuffer(buffer, len, withSpace)
#define emberAfPluginGlobalAddressPrefixDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG)


// Generated functions for use within plugin HAL Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY)
#define emberAfPluginHalLibraryPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY, __VA_ARGS__)
#define emberAfPluginHalLibraryPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginHalLibraryFlush()
#define emberAfPluginHalLibraryDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY) ) { x; }
#define emberAfPluginHalLibraryPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY, (buffer), (len), (withSpace))
#define emberAfPluginHalLibraryPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY, (buffer))
#else
#define emberAfPluginHalLibraryPrint(...)
#define emberAfPluginHalLibraryPrintln(...)
#define emberAfPluginHalLibraryFlush()
#define emberAfPluginHalLibraryDebugExec(x)
#define emberAfPluginHalLibraryPrintBuffer(buffer, len, withSpace)
#define emberAfPluginHalLibraryPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HAL_LIBRARY)


// Generated functions for use within plugin Heartbeat
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HEARTBEAT)
#define emberAfPluginHeartbeatPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_HEARTBEAT, __VA_ARGS__)
#define emberAfPluginHeartbeatPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_HEARTBEAT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginHeartbeatFlush()
#define emberAfPluginHeartbeatDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_HEARTBEAT) ) { x; }
#define emberAfPluginHeartbeatPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_HEARTBEAT, (buffer), (len), (withSpace))
#define emberAfPluginHeartbeatPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_HEARTBEAT, (buffer))
#else
#define emberAfPluginHeartbeatPrint(...)
#define emberAfPluginHeartbeatPrintln(...)
#define emberAfPluginHeartbeatFlush()
#define emberAfPluginHeartbeatDebugExec(x)
#define emberAfPluginHeartbeatPrintBuffer(buffer, len, withSpace)
#define emberAfPluginHeartbeatPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HEARTBEAT)


// Generated functions for use within plugin ICMP CLI
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ICMP_CLI)
#define emberAfPluginIcmpCliPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_ICMP_CLI, __VA_ARGS__)
#define emberAfPluginIcmpCliPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_ICMP_CLI,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginIcmpCliFlush()
#define emberAfPluginIcmpCliDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_ICMP_CLI) ) { x; }
#define emberAfPluginIcmpCliPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_ICMP_CLI, (buffer), (len), (withSpace))
#define emberAfPluginIcmpCliPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_ICMP_CLI, (buffer))
#else
#define emberAfPluginIcmpCliPrint(...)
#define emberAfPluginIcmpCliPrintln(...)
#define emberAfPluginIcmpCliFlush()
#define emberAfPluginIcmpCliDebugExec(x)
#define emberAfPluginIcmpCliPrintBuffer(buffer, len, withSpace)
#define emberAfPluginIcmpCliPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ICMP_CLI)


// Generated functions for use within plugin ICMP Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG)
#define emberAfPluginIcmpDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG, __VA_ARGS__)
#define emberAfPluginIcmpDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginIcmpDebugFlush()
#define emberAfPluginIcmpDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG) ) { x; }
#define emberAfPluginIcmpDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG, (buffer), (len), (withSpace))
#define emberAfPluginIcmpDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG, (buffer))
#else
#define emberAfPluginIcmpDebugPrint(...)
#define emberAfPluginIcmpDebugPrintln(...)
#define emberAfPluginIcmpDebugFlush()
#define emberAfPluginIcmpDebugDebugExec(x)
#define emberAfPluginIcmpDebugPrintBuffer(buffer, len, withSpace)
#define emberAfPluginIcmpDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_ICMP_DEBUG)


// Generated functions for use within plugin Idle/Sleep
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP)
#define emberAfPluginIdleSleepPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP, __VA_ARGS__)
#define emberAfPluginIdleSleepPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginIdleSleepFlush()
#define emberAfPluginIdleSleepDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP) ) { x; }
#define emberAfPluginIdleSleepPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP, (buffer), (len), (withSpace))
#define emberAfPluginIdleSleepPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP, (buffer))
#else
#define emberAfPluginIdleSleepPrint(...)
#define emberAfPluginIdleSleepPrintln(...)
#define emberAfPluginIdleSleepFlush()
#define emberAfPluginIdleSleepDebugExec(x)
#define emberAfPluginIdleSleepPrintBuffer(buffer, len, withSpace)
#define emberAfPluginIdleSleepPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_IDLE_SLEEP)


// Generated functions for use within plugin LED
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_LED)
#define emberAfPluginLedPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_LED, __VA_ARGS__)
#define emberAfPluginLedPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_LED,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginLedFlush()
#define emberAfPluginLedDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_LED) ) { x; }
#define emberAfPluginLedPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_LED, (buffer), (len), (withSpace))
#define emberAfPluginLedPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_LED, (buffer))
#else
#define emberAfPluginLedPrint(...)
#define emberAfPluginLedPrintln(...)
#define emberAfPluginLedFlush()
#define emberAfPluginLedDebugExec(x)
#define emberAfPluginLedPrintBuffer(buffer, len, withSpace)
#define emberAfPluginLedPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_LED)


// Generated functions for use within plugin Main
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MAIN)
#define emberAfPluginMainPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_MAIN, __VA_ARGS__)
#define emberAfPluginMainPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_MAIN,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginMainFlush()
#define emberAfPluginMainDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_MAIN) ) { x; }
#define emberAfPluginMainPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_MAIN, (buffer), (len), (withSpace))
#define emberAfPluginMainPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_MAIN, (buffer))
#else
#define emberAfPluginMainPrint(...)
#define emberAfPluginMainPrintln(...)
#define emberAfPluginMainFlush()
#define emberAfPluginMainDebugExec(x)
#define emberAfPluginMainPrintBuffer(buffer, len, withSpace)
#define emberAfPluginMainPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MAIN)


// Generated functions for use within plugin mbed TLS Cryptographic Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY)
#define emberAfPluginMbedtlsLibraryPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY, __VA_ARGS__)
#define emberAfPluginMbedtlsLibraryPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginMbedtlsLibraryFlush()
#define emberAfPluginMbedtlsLibraryDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY) ) { x; }
#define emberAfPluginMbedtlsLibraryPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY, (buffer), (len), (withSpace))
#define emberAfPluginMbedtlsLibraryPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY, (buffer))
#else
#define emberAfPluginMbedtlsLibraryPrint(...)
#define emberAfPluginMbedtlsLibraryPrintln(...)
#define emberAfPluginMbedtlsLibraryFlush()
#define emberAfPluginMbedtlsLibraryDebugExec(x)
#define emberAfPluginMbedtlsLibraryPrintBuffer(buffer, len, withSpace)
#define emberAfPluginMbedtlsLibraryPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MBEDTLS_LIBRARY)


// Generated functions for use within plugin Manufacturing Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY)
#define emberAfPluginMfglibLibraryPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY, __VA_ARGS__)
#define emberAfPluginMfglibLibraryPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginMfglibLibraryFlush()
#define emberAfPluginMfglibLibraryDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY) ) { x; }
#define emberAfPluginMfglibLibraryPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY, (buffer), (len), (withSpace))
#define emberAfPluginMfglibLibraryPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY, (buffer))
#else
#define emberAfPluginMfglibLibraryPrint(...)
#define emberAfPluginMfglibLibraryPrintln(...)
#define emberAfPluginMfglibLibraryFlush()
#define emberAfPluginMfglibLibraryDebugExec(x)
#define emberAfPluginMfglibLibraryPrintBuffer(buffer, len, withSpace)
#define emberAfPluginMfglibLibraryPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MFGLIB_LIBRARY)


// Generated functions for use within plugin Network Management CLI
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI)
#define emberAfPluginNetworkManagementCliPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI, __VA_ARGS__)
#define emberAfPluginNetworkManagementCliPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginNetworkManagementCliFlush()
#define emberAfPluginNetworkManagementCliDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI) ) { x; }
#define emberAfPluginNetworkManagementCliPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI, (buffer), (len), (withSpace))
#define emberAfPluginNetworkManagementCliPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI, (buffer))
#else
#define emberAfPluginNetworkManagementCliPrint(...)
#define emberAfPluginNetworkManagementCliPrintln(...)
#define emberAfPluginNetworkManagementCliFlush()
#define emberAfPluginNetworkManagementCliDebugExec(x)
#define emberAfPluginNetworkManagementCliPrintBuffer(buffer, len, withSpace)
#define emberAfPluginNetworkManagementCliPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_NETWORK_MANAGEMENT_CLI)


// Generated functions for use within plugin Scan Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG)
#define emberAfPluginScanDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG, __VA_ARGS__)
#define emberAfPluginScanDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginScanDebugFlush()
#define emberAfPluginScanDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG) ) { x; }
#define emberAfPluginScanDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG, (buffer), (len), (withSpace))
#define emberAfPluginScanDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG, (buffer))
#else
#define emberAfPluginScanDebugPrint(...)
#define emberAfPluginScanDebugPrintln(...)
#define emberAfPluginScanDebugFlush()
#define emberAfPluginScanDebugDebugExec(x)
#define emberAfPluginScanDebugPrintBuffer(buffer, len, withSpace)
#define emberAfPluginScanDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SCAN_DEBUG)


// Generated functions for use within plugin Serial
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SERIAL)
#define emberAfPluginSerialPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_SERIAL, __VA_ARGS__)
#define emberAfPluginSerialPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_SERIAL,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginSerialFlush()
#define emberAfPluginSerialDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_SERIAL) ) { x; }
#define emberAfPluginSerialPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_SERIAL, (buffer), (len), (withSpace))
#define emberAfPluginSerialPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_SERIAL, (buffer))
#else
#define emberAfPluginSerialPrint(...)
#define emberAfPluginSerialPrintln(...)
#define emberAfPluginSerialFlush()
#define emberAfPluginSerialDebugExec(x)
#define emberAfPluginSerialPrintBuffer(buffer, len, withSpace)
#define emberAfPluginSerialPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SERIAL)


// Generated functions for use within plugin Simulated EEPROM version 1 Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1)
#define emberAfPluginSimEeprom1Print(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1, __VA_ARGS__)
#define emberAfPluginSimEeprom1Println(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginSimEeprom1Flush()
#define emberAfPluginSimEeprom1DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1) ) { x; }
#define emberAfPluginSimEeprom1PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1, (buffer), (len), (withSpace))
#define emberAfPluginSimEeprom1PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1, (buffer))
#else
#define emberAfPluginSimEeprom1Print(...)
#define emberAfPluginSimEeprom1Println(...)
#define emberAfPluginSimEeprom1Flush()
#define emberAfPluginSimEeprom1DebugExec(x)
#define emberAfPluginSimEeprom1PrintBuffer(buffer, len, withSpace)
#define emberAfPluginSimEeprom1PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1)


// Generated functions for use within plugin Stateless Address Autoconfiguration (SLAAC) Client
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT)
#define emberAfPluginSlaacClientPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT, __VA_ARGS__)
#define emberAfPluginSlaacClientPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginSlaacClientFlush()
#define emberAfPluginSlaacClientDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT) ) { x; }
#define emberAfPluginSlaacClientPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT, (buffer), (len), (withSpace))
#define emberAfPluginSlaacClientPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT, (buffer))
#else
#define emberAfPluginSlaacClientPrint(...)
#define emberAfPluginSlaacClientPrintln(...)
#define emberAfPluginSlaacClientFlush()
#define emberAfPluginSlaacClientDebugExec(x)
#define emberAfPluginSlaacClientPrintBuffer(buffer, len, withSpace)
#define emberAfPluginSlaacClientPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SLAAC_CLIENT)


// Generated functions for use within plugin TFTP Bootload Target
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET)
#define emberAfPluginTftpBootloadTargetPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET, __VA_ARGS__)
#define emberAfPluginTftpBootloadTargetPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginTftpBootloadTargetFlush()
#define emberAfPluginTftpBootloadTargetDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET) ) { x; }
#define emberAfPluginTftpBootloadTargetPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET, (buffer), (len), (withSpace))
#define emberAfPluginTftpBootloadTargetPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET, (buffer))
#else
#define emberAfPluginTftpBootloadTargetPrint(...)
#define emberAfPluginTftpBootloadTargetPrintln(...)
#define emberAfPluginTftpBootloadTargetFlush()
#define emberAfPluginTftpBootloadTargetDebugExec(x)
#define emberAfPluginTftpBootloadTargetPrintBuffer(buffer, len, withSpace)
#define emberAfPluginTftpBootloadTargetPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_TFTP_BOOTLOAD_TARGET)


// Generated functions for use within plugin Thread Stack Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_THREAD_STACK)
#define emberAfPluginThreadStackPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_THREAD_STACK, __VA_ARGS__)
#define emberAfPluginThreadStackPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_THREAD_STACK,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginThreadStackFlush()
#define emberAfPluginThreadStackDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_THREAD_STACK) ) { x; }
#define emberAfPluginThreadStackPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_THREAD_STACK, (buffer), (len), (withSpace))
#define emberAfPluginThreadStackPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_THREAD_STACK, (buffer))
#else
#define emberAfPluginThreadStackPrint(...)
#define emberAfPluginThreadStackPrintln(...)
#define emberAfPluginThreadStackFlush()
#define emberAfPluginThreadStackDebugExec(x)
#define emberAfPluginThreadStackPrintBuffer(buffer, len, withSpace)
#define emberAfPluginThreadStackPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_THREAD_STACK)


// Generated functions for use within plugin UDP CLI
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_UDP_CLI)
#define emberAfPluginUdpCliPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_UDP_CLI, __VA_ARGS__)
#define emberAfPluginUdpCliPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_UDP_CLI,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginUdpCliFlush()
#define emberAfPluginUdpCliDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_UDP_CLI) ) { x; }
#define emberAfPluginUdpCliPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_UDP_CLI, (buffer), (len), (withSpace))
#define emberAfPluginUdpCliPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_UDP_CLI, (buffer))
#else
#define emberAfPluginUdpCliPrint(...)
#define emberAfPluginUdpCliPrintln(...)
#define emberAfPluginUdpCliFlush()
#define emberAfPluginUdpCliDebugExec(x)
#define emberAfPluginUdpCliPrintBuffer(buffer, len, withSpace)
#define emberAfPluginUdpCliPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_UDP_CLI)


// Generated functions for use within plugin Version Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG)
#define emberAfPluginVersionDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG, __VA_ARGS__)
#define emberAfPluginVersionDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginVersionDebugFlush()
#define emberAfPluginVersionDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG) ) { x; }
#define emberAfPluginVersionDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG, (buffer), (len), (withSpace))
#define emberAfPluginVersionDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG, (buffer))
#else
#define emberAfPluginVersionDebugPrint(...)
#define emberAfPluginVersionDebugPrintln(...)
#define emberAfPluginVersionDebugFlush()
#define emberAfPluginVersionDebugDebugExec(x)
#define emberAfPluginVersionDebugPrintBuffer(buffer, len, withSpace)
#define emberAfPluginVersionDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_VERSION_DEBUG)


// Generated functions for use within area Core
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CORE)
#define emberAfCorePrint(...) emberAfPrint(EMBER_AF_PRINT_CORE, __VA_ARGS__)
#define emberAfCorePrintln(...) emberAfPrintln(EMBER_AF_PRINT_CORE,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCoreFlush()
#define emberAfCoreDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CORE) ) { x; }
#define emberAfCorePrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CORE, (buffer), (len), (withSpace))
#define emberAfCorePrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CORE, (buffer))
#else
#define emberAfCorePrint(...)
#define emberAfCorePrintln(...)
#define emberAfCoreFlush()
#define emberAfCoreDebugExec(x)
#define emberAfCorePrintBuffer(buffer, len, withSpace)
#define emberAfCorePrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CORE)


// Generated functions for use within area Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_DEBUG)
#define emberAfDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_DEBUG, __VA_ARGS__)
#define emberAfDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfDebugFlush()
#define emberAfDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_DEBUG) ) { x; }
#define emberAfDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_DEBUG, (buffer), (len), (withSpace))
#define emberAfDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_DEBUG, (buffer))
#else
#define emberAfDebugPrint(...)
#define emberAfDebugPrintln(...)
#define emberAfDebugFlush()
#define emberAfDebugDebugExec(x)
#define emberAfDebugPrintBuffer(buffer, len, withSpace)
#define emberAfDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_DEBUG)


// Generated functions for use within area Application
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_APP)
#define emberAfAppPrint(...) emberAfPrint(EMBER_AF_PRINT_APP, __VA_ARGS__)
#define emberAfAppPrintln(...) emberAfPrintln(EMBER_AF_PRINT_APP,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfAppFlush()
#define emberAfAppDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_APP) ) { x; }
#define emberAfAppPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_APP, (buffer), (len), (withSpace))
#define emberAfAppPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_APP, (buffer))
#else
#define emberAfAppPrint(...)
#define emberAfAppPrintln(...)
#define emberAfAppFlush()
#define emberAfAppDebugExec(x)
#define emberAfAppPrintBuffer(buffer, len, withSpace)
#define emberAfAppPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_APP)


// Generated functions for use within area Custom messages (1)
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM1)
#define emberAfCustom1Print(...) emberAfPrint(EMBER_AF_PRINT_CUSTOM1, __VA_ARGS__)
#define emberAfCustom1Println(...) emberAfPrintln(EMBER_AF_PRINT_CUSTOM1,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCustom1Flush()
#define emberAfCustom1DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CUSTOM1) ) { x; }
#define emberAfCustom1PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CUSTOM1, (buffer), (len), (withSpace))
#define emberAfCustom1PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CUSTOM1, (buffer))
#else
#define emberAfCustom1Print(...)
#define emberAfCustom1Println(...)
#define emberAfCustom1Flush()
#define emberAfCustom1DebugExec(x)
#define emberAfCustom1PrintBuffer(buffer, len, withSpace)
#define emberAfCustom1PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM1)


// Generated functions for use within area Custom messages (2)
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM2)
#define emberAfCustom2Print(...) emberAfPrint(EMBER_AF_PRINT_CUSTOM2, __VA_ARGS__)
#define emberAfCustom2Println(...) emberAfPrintln(EMBER_AF_PRINT_CUSTOM2,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCustom2Flush()
#define emberAfCustom2DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CUSTOM2) ) { x; }
#define emberAfCustom2PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CUSTOM2, (buffer), (len), (withSpace))
#define emberAfCustom2PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CUSTOM2, (buffer))
#else
#define emberAfCustom2Print(...)
#define emberAfCustom2Println(...)
#define emberAfCustom2Flush()
#define emberAfCustom2DebugExec(x)
#define emberAfCustom2PrintBuffer(buffer, len, withSpace)
#define emberAfCustom2PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM2)


// Generated functions for use within area Custom messages (3)
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM3)
#define emberAfCustom3Print(...) emberAfPrint(EMBER_AF_PRINT_CUSTOM3, __VA_ARGS__)
#define emberAfCustom3Println(...) emberAfPrintln(EMBER_AF_PRINT_CUSTOM3,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCustom3Flush()
#define emberAfCustom3DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CUSTOM3) ) { x; }
#define emberAfCustom3PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CUSTOM3, (buffer), (len), (withSpace))
#define emberAfCustom3PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CUSTOM3, (buffer))
#else
#define emberAfCustom3Print(...)
#define emberAfCustom3Println(...)
#define emberAfCustom3Flush()
#define emberAfCustom3DebugExec(x)
#define emberAfCustom3PrintBuffer(buffer, len, withSpace)
#define emberAfCustom3PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM3)


#endif // __EMBER_AF_DEBUG_PRINTING_CONFIGURATION__
