// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __THREAD_EVENTS__
#define __THREAD_EVENTS__


// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void stateEventHandler(void);
extern EmberEventControl stateEventControl;

void updateDisplayEventHandler(void);
extern EmberEventControl updateDisplayEventControl;

void emberAfPluginButton0EventHandler(void);
extern EmberEventControl emberAfPluginButton0EventControl;

void emberAfPluginButton1EventHandler(void);
extern EmberEventControl emberAfPluginButton1EventControl;

void emberAfPluginHeartbeatNodeTypeEventHandler(void);
extern EmberEventControl emberAfPluginHeartbeatNodeTypeEventControl;

void emBootloadEventHandler(void);
extern EmberEventControl emBootloadEvent;



const EmberEventData emAppEvents[] = {
  {&stateEventControl, stateEventHandler},
  {&updateDisplayEventControl, updateDisplayEventHandler},
  {&emberAfPluginButton0EventControl, emberAfPluginButton0EventHandler},
  {&emberAfPluginButton1EventControl, emberAfPluginButton1EventHandler},
  {&emberAfPluginHeartbeatNodeTypeEventControl, emberAfPluginHeartbeatNodeTypeEventHandler},
  {&emBootloadEvent, emBootloadEventHandler},
  {NULL, NULL}
};
#endif // __THREAD_EVENTS__
